In [39]:
import pandas as pd
import numpy as np

In [40]:
df=pd.read_csv('/Users/hexiaoyu/Desktop/Courses/INSY- DATA MINING/cereals.CSV')
# examining the nutrition showed on the package has any relationship with the cereals rating using linear regression 

In [41]:
df=df.dropna()

In [42]:
df.head()

Name Manuf Type  Calories  Protein  Fat  Sodium  \
0                  100%_Bran     N    C         70        4    1     130   
1          100%_Natural_Bran     Q    C        120        3    5      15   
2                   All-Bran     K    C         70        4    1     260   
3  All-Bran_with_Extra_Fiber     K    C         50        4    0     140   
5    Apple_Cinnamon_Cheerios     G    C        110        2    2     180   

   Fiber  Carbo  Sugars  ...  Weight  Cups     Rating  Cold  Nabisco  Quaker  \
0   10.0    5.0     6.0  ...     1.0  0.33  68.402973     1        1       0   
1    2.0    8.0     8.0  ...     1.0  1.00  33.983679     1        0       1   
2    9.0    7.0     5.0  ...     1.0  0.33  59.425505     1        0       0   
3   14.0    8.0     0.0  ...     1.0  0.50  93.704912     1        0       0   
5    1.5   10.5    10.0  ...     1.0  0.75  29.509541     1        0       0   

   Kelloggs  GeneralMills  Ralston  AHFP  
0         0             0        0     0  
1         0             0        0     0  
2         1             0        0     0  
3         1             0        0     0  
5         0             1        0     0  

[5 rows x 23 columns]

In [43]:
# construct x and y 
X=df.iloc[:,3:12]
y=df['Rating']

In [44]:
#standarize predictor 
from sklearn.preprocessing import StandardScaler
### Type your code here ###
scaler=StandardScaler()
scaled_X = scaler.fit_transform(X) 
scaled_X = pd.DataFrame(scaled_X, columns=X.columns) 
scaled_X

Calories   Protein  Fat    Sodium     Fiber     Carbo    Sugars    Potass  \
0  -1.878652  1.391180  0.0 -0.393692  3.250706 -2.517206 -0.255940  2.578001   
1   0.658214  0.455295  4.0 -1.792572 -0.072986 -1.741067  0.206001  0.518288   
2  -1.878652  1.391180  0.0  1.187651  2.835245 -1.999780 -0.486911  3.146198   
3  -2.893399  1.391180 -1.0 -0.272050  4.912553 -1.741067 -1.641763  3.288247   
4   0.150841 -0.480589  1.0  0.214517 -0.280717 -1.094285  0.667942 -0.405032   
..       ...       ...  ...       ...       ...       ...       ...       ...   
69  0.150841 -0.480589  0.0  1.066009 -0.903910  1.622199 -0.948852 -0.547081   
70  0.150841 -1.416474  0.0 -0.272050 -0.903910 -0.447503  1.129883 -1.044254   
71 -0.356533  0.455295  0.0  0.822725  0.342475  0.587348 -0.948852  0.234189   
72 -0.356533  0.455295  0.0  0.457800  0.342475  0.587348 -0.948852  0.163165   
73  0.150841 -0.480589  0.0  0.457800 -0.488448  0.328635  0.206001 -0.547081   

    Vitamins  
0  -0.183083  
1  -1.312098  
2  -0.183083  
3  -0.183083  
4  -0.183083  
..       ...  
69 -0.183083  
70 -0.183083  
71 -0.183083  
72 -0.183083  
73 -0.183083  

[74 rows x 9 columns]

In [45]:
### model building ###
from sklearn.linear_model import LinearRegression
Im = LinearRegression()
model = Im. fit(scaled_X, y) # fit the model 
y_pred = model.predict(scaled_X)

In [46]:
y_pred

array([68.40297282, 33.98367896, 59.42550472, 93.70491234, 29.50954066,
       33.17409435, 37.0385619 , 49.12025292, 53.31381285, 18.04285082,
       50.76499891, 19.8235727 , 40.40020799, 22.7364464 , 41.44501943,
       45.86332453, 35.78279074, 22.39651288, 40.44877238, 46.89564363,
       36.17619619, 44.33085567, 32.20758153, 31.43597282, 58.34514142,
       40.91704688, 41.0154918 , 28.02576464, 35.2524438 , 23.80404307,
       52.07689664, 53.37100724, 45.8117159 , 21.87129221, 31.07221727,
       28.74241356, 36.5236833 , 36.4715121 , 39.24111428, 45.32807423,
       26.7345154 , 54.85091715, 37.13686307, 34.13976445, 30.31335105,
       40.10596491, 29.92428522, 40.69232044, 59.64283672, 30.45084348,
       37.84059397, 41.50354003, 60.75611179, 63.00564526, 49.51187437,
       39.25919733, 39.70339974, 55.33314201, 41.99893296, 40.56015889,
       68.2358847 , 74.47294875, 72.80178696, 31.23005446, 53.13132353,
       59.36399342, 38.83974546, 28.59278471, 46.65884421, 39.10

In [47]:
# View coefficient results 
print(pd.DataFrame(model.coef_, scaled_X.columns, columns=['Coefficients']))

          Coefficients
Calories     -4.389750
Protein       3.497412
Fat          -1.691408
Sodium       -4.479770
Fiber         8.288322
Carbo         4.222640
Sugars       -3.138475
Potass       -2.393069
Vitamins     -1.133997


that's the end of the model prediction part from there we could interpret the coefficient and the connection between predictors 
and the targeted variable. 


in this case, most obvious trends shows that high calories, high sodium reduce the cereal rating while high fiber, carbo and protein have positive effect on the rating especially the fiber. 


reflection: this model we do not have the muticollinearity test among the predictor, the results could be different if there is collinearity exists. 

In [48]:
### logistic regression model ### (classification) 
df['binary_rating']=df['Rating'].apply(lambda x: 1 if x>50 else 0)
y = df['binary_rating']

In [53]:
from sklearn.linear_model import LogisticRegression
Ir = LogisticRegression (penalty=None)
model_Ir = Ir. fit(scaled_X,y)
y_pred = model_Ir.predict(scaled_X)
y_pred


array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 0])

In [50]:
y_pred_prob = model_Ir.predict_proba(scaled_X)
y_pred_prob
# the probability of being in 0 or 1 


array([[0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 4.92768167e-30],
       [5.78037618e-11, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.45484112e-41],
       [1.00000000e+00, 6.43944656e-35],
       [1.00000000e+00, 5.46539891e-26],
       [9.99999999e-01, 1.48202225e-09],
       [1.57327980e-05, 9.99984267e-01],
       [1.00000000e+00, 2.04917426e-63],
       [1.46666948e-03, 9.98533331e-01],
       [1.00000000e+00, 2.09256404e-59],
       [1.00000000e+00, 1.54181973e-19],
       [1.00000000e+00, 1.19056979e-56],
       [1.00000000e+00, 5.17318283e-16],
       [9.99999998e-01, 2.30118056e-09],
       [1.00000000e+00, 1.42576060e-28],
       [1.00000000e+00, 2.80797593e-57],
       [1.00000000e+00, 9.82821469e-20],
       [9.99848168e-01, 1.51831885e-04],
       [1.00000000e+00, 2.54381426e-30],
       [1.00000000e+00, 1.74528874e-12],
       [1.00000000e+00, 4.59443155e-38],
       [1.00000000e+00, 2.56014976e-37],
       [0.000000

In [51]:
print(pd.DataFrame(model_Ir.coef_[0], scaled_X.columns, columns=['Coefficients']))


          Coefficients
Calories     -1.911876
Protein      14.252932
Fat         -13.835753
Sodium      -21.063515
Fiber        33.535104
Carbo         8.419365
Sugars      -28.533516
Potass      -10.169386
Vitamins     -7.172873


the coefficient of logistic regression interpretation: the positive coefficient means as 1 unit of variable increase, it increase the likelihood to be 1. vice versa, the negative coefficient means that 1 unit increase, it decrease the likelihood to be 1 ( more likely to be 0)  

in this case, we can tell that as sugar increase, the rating would most likely to be 0 which indicating the rating below 50. while the fiber is the opposite side. considering the factors influencing rating surpass the 50 threhold or not, fiber, protein has the most positive power while the sugar, solium has the most negative power consequently. 